== Advantages

Most of the organizations that work with DAPs are, like OPeNDAP, not for profit and open source.
As such, there's a lot of overlap between different systems. That being said, there
are a few areas where Hyrax really shines.


// For example, when we saw the
// THREDDS catalog implemented by UNIDATA, we thought 
// we implemented
// our own THREDDS catalog 
// They saw protocol that devs at unidata built, so they said
// we're gonna implement that as well, because it's really smart, also NCML aggregation technology.
// We are providing a second implementation of those protocols. One askpect of providing
// support for online data.

// The reason we created our own implementation and why it's important
// is because it provides a truthing mechanism for "can this idea be implemented by other people"
// "is it documented well enough."

=== Extendability

Hyrax's primary advantage lies in its extendability. We have designed Hyrax to be as abstract as possible,
meaning it can handle virtually any data structure or source without undergoing extensive modifications.
We've proved Hyrax's extendability with
link:/hyrax-about#source-data-formats[several data handlers that we've already written].

=== Support

Furthermore, if you need assistance with Hyrax, we're here to help.
You can send questions to mailto:support@opendap.org[our support email], where they'll be addressed by an OPeNDAP developer.
We try to respond to your inquiries within a few hours, either with an answer,
a request for more information, or a note letting you know we're looking into the issue.

For tasks that require a heavier lift than simple support, OPeNDAP provides consulting services.
We can work with you to implement new features and are willing to negotiate on time and materials,
as well as fixed-price contracts. For more information about the levels of support that OPeNDAP provides,
check out our link:/support[Support page].

=== Reliability

Finally, Hyrax is hardened and battle-tested. Not only can it be easily extended to support
many data structures and sources, but it is highly-integrated with NASA, which has thousands of
highly-structured datasets that are currently accessible via the DAP.
