== Features

=== THREDDS Catalog Support

Hyrax supports the THREDDS catalogs. It can serve user supplied static catalogs and it will dynamically generate THREDDS catalogs of its internal holdings.

=== Source Data Formats

The BES can ingest source data stored as...

* HDF4
* HDF4-EOS
* HDF5
* HDF5-EOS
* NetCDF-3
* NetCDF-4
* CEDAR
* FITS
* Comma Separated Values
* Raw ASCII and binary formats.

Because of Hyrax’s extensible design, it’s easy to add new source data formats.

=== Data Retrieval Formats

Hyrax is able to return data in...

* DAP
* DAP4
* NetCDF-3
* NetCDF-4
* JSON
* CSV
* ASCII formats.

You can also add your own response types.

// Administrator’s interface: Control and dynamically update Hyrax from a convenient web interface. See the Admin interface documentation.

=== Dataset Aggregation

Collections of related data resources can be collected into a single dataset using the aggregation features. Typically these are formed for geographic tiles, time series, etc.

=== Adding and Modifying Dataset Content

Datasets can be modified by the server without having to actually change the underlying files. These views are independently accessible from the original data. Both dataset metadata and data values can be added or changed.

=== w10n

Hyrax comes with a complete w10n service stack. W10n navigation is supported through the default catalog where all datasets and "structure" variables appear as graph nodes. Data can be acquired for atomic types or arrays of atomic types in a number of formats.

=== Networking and Metadata

==== Gateway

Hyrax supports a gateway feature that allows it to provide DAP (and other Hyrax) services for remotely held datasets that are stored in any of Hyrax’s source data formats.

==== RDF

Hyrax provides RDF descriptions of it’s data holdings. These can enable semantic web tools to operate upon the metadata content held in the server.

==== JSON

Both metadata and data are now available in a JSON encoding.

==== WMS Services

Hyrax now supports WMS services via integration with ncWMS.

=== Server-side Functionality

==== geogrid

Subset applicable DAP Grids using latitude and longitude values.

=== grid

Subset any DAP Grid object using the values of it’s map vectors.

==== linear_scale

Apply a linear equation to the data returned, including automatic use of CF attributes.

==== version

The version function provides a list of the server-side processing functions available.

=== Configureability

==== Extensible WebStart Functionality for Data Clients

Hyrax provides WebStart functionality for a number of Java based DAP clients. It’s simple to add new clients to the list that Hyrax supports.

==== Extensible/Configurable Web Interface

The web interface for both Hyrax and the administrator’s interface can be customized using CSS and XSL. You can add your organizations logo and specialize the colors and fonts in the presentation of data sets.

=== Support

If there is a feature you would like to see but don’t, let us know: support@opendap.org or opendap-tech@opendap.org. (You need to subscribe first.)








