== Architecture

As we discussed above, Hyrax is split into two distinct pieces of software: the BES and the OLFS.
There were a few reasons we decided to split Hyrax's functionality:

{{
  "sectionType": "html",
  "title": "architecture",
  "id": "hyrax-architecture",
  "filename": "hyrax-architecture.html",
  "parsedFile": ""
}}

=== Do One Thing Well

Following the Unix design paradigm, we have developed two distinct pieces of software, each of which
does one thing well:

* The OLFS uses the Java servlet mechanism to hand off requests from a general web daemon to the BES. 
It looks at each request and formulates a query to a second server, the BES. 


* The BES on the other hand is high-performance server software from HAO.
It reads data from the data stores and returns DAP-compliant responses to the OLFS.

In turn, the OLFS may pass these responses back to the requestor with little or no modification,
or it may use them to build more complex responses.

// The nature of the Inter Process Communication (IPC) between the OLFS and BES is such that they should both be on the same machine or able to communicate over a very high-bandwidth channel.

=== Security

Our second consideration had to do with security. The OLFS is the point of contact for the entire world,
meaning that, while very secure in its own right, it is exposed to security threats. The BES, on the other hand,
is only accessible via the OLFS. If the OLFS is breached, intruders will be able to access data,
but they will only be able to inflict minimal damage.
