:Leonard Porrello <lporrel@gmail.com>:


////
TODO: We should include roughtly the same level of information here for the BES as for the OLFS.
Also, we should look at the software distribution page and decide if that's the place to put the
'how to start the software' information or if this is the place. jhrg 9/15/17
////

////
== Introduction

TODO: Introduce libdap and the BES as the OLFS is introduced in the 
document Master_Hyrax_OLFS_Installation.
////

== BES Installation

=== 1. Download

It is necessary that you download and install both the _libdap_ and _BES_ binaries.

. Visit the 
  https://www.opendap.org/software/hyrax-data-server#block-hyraxversions-menu[Hyrax
  Data Server Page].
. Select the most recent in the list of *Available Versions*.
. Scroll down the following page until you reach the section entitled 
  *Binaries for Hyrax x.x.x*, then continue scrolling until you
  see the heading titled *BES*.
. You need to download both the _libdap_ and _BES_ RPMs which should be named
  _libdap-x.x.x_ and _bes-x.x.x_.
. The downloaded files should be named something like
  _libdap-x.x.x.el6.x86_64.rpm_ and _bes-x.x.x.static.el6.x86_64.rpm_.

WARNING: In order to install the RPMs on your system, you *must* be running
a 64bit OS. If you are running 32bit OS, attempting to install the 
_libdap_ and _BES_ RPMs will result in errors.

////
TODO: Supplement/modify the following information as necessary. It was taken
from the Hyrax install page.
////
=== 2. Install

. Use yum to install the libdap and bes RPMs: +
  `sudo yum install libdap-3.x.x.rpm bes-3.x.x.rpm`).
. At this point you can test the BES by typing the following into a terminal:
.. start it: +
   `sudo service besd start` +
   (Or use the script in _/etc/init.d with sudo_: _/etc/init.d/besd start_)
.. connect using a simple client: +
   `bescmdln`
.. get version information: +
   `BESClient> show version`
.. exit from `bescmdln`: +
   `BESClient> exit`
