== Advantages

Most of the organizations that work with DAPs are, like OPeNDAP, not for profit and open source.
As such, there's a lot of overlap between different systems. That being said, there
are a few areas where Hyrax really shines.


// For example, when we saw the
// THREDDS catalog implemented by UNIDATA, we thought 
// we implemented
// our own THREDDS catalog 
// They saw protocol that devs at unidata built, so they said
// we're gonna implement that as well, because it's really smart, also NCML aggregation technology.
// We are providing a second implementation of those protocols. One askpect of providing
// support for online data.

// The reason we created our own implementation and why it's important
// is because it provides a truthing mechanism for "can this idea be implemented by other people"
// "is it documented well enough."

=== Extendability

Hyrax's primary advantage lies in its extendability. We have designed Hyrax to be as abstract as possible,
meaning it can handle virtually any data structure or source without undergoing extensive modifications.
Hyrax also provides WebStart functionality for a number of Java-based DAP clients.
It's simple to add new clients to the list that Hyrax supports.

Out of the box, Hyrax can ingest source data stored as...

* HDF4
* HDF4-EOS
* HDF5
* HDF5-EOS
* NetCDF-3
* NetCDF-4
* CEDAR
* FITS
* Comma Separated Values
* Raw ASCII and binary formats.

And it's able to return data in several formats, such as...

* DAP
* DAP4
* NetCDF-3
* NetCDF-4
* JSON
* CSV
* ASCII

We've also implemented our own THREDDS catalog support.

=== Reliability

Finally, Hyrax is hardened and battle-tested. Not only can it be easily extended to support
many data structures and sources, but it is highly-integrated with NASA, which has thousands of
highly-structured datasets that are currently accessible via the DAP.


=== Support

If you need assistance with Hyrax, we're here to help.
You can send questions to mailto:support@opendap.org[our support email], where they'll be addressed by an OPeNDAP developer.
We try to respond to your inquiries within a few hours, either with an answer,
a request for more information, or a note letting you know we're looking into the issue.

Furthermore, for tasks that require a heavier lift than simple support, OPeNDAP provides consulting services.
We can work with you to implement new features and are willing to negotiate on time and materials,
as well as fixed-price contracts. For more information about the levels of support that OPeNDAP provides,
check out our link:/support[Support page].
