== OPeNDAP Software

On this page you will find background information about the software
we have available for download. This information includes the public key we use
to sign our software, access to the complete archive and information
for software developers who use our toolkits about our open software revision system.

We manage several different open-source software packages,
and you can download either source code or pre-built binaries from here.
The following packages have their own pages:

|=============
a|link:/software/hyrax[Hyrax] |Our modular data server.
a|link:/software/libdap[libdap] |Software development toolkit that can be used to build clients and servers using C++.
|=============

We also maintain a list of software developed by other groups
that can read from OPeNDAP servers, and that there are several
other groups that make servers besides us.

== Public Key

OPeNDAP's Public Key is available here. We now (November 2007) sign all of
our software releases using gpg and a key created just for this purpose.
The public key is bound to the email address security@opendap.org.
The address is 'real' in the sense that email sent there will be answered,
although we ask that support questions be sent to the support@opendap.org
address instead. To verify a particular software package using its digital signature:

* Import the security at opendap.org public key into your key ring
(see the gpg documentation for help on that);
* Download both the package and the .sig signature file and put them
in the same directory; and
* Run `gpg --verify <signature file name>` in the directory with those files.

The result should be a message telling you that the signature is valid, who signed it and when it was signed. If you don't get a message saying the signature is valid, double check that you have installed the public key correctly, have the file and its signature in the same directory and have not renamed the file (or signature). If, after that, you're still not getting a message that the signature is valid, please contact us.

== Software Archive

The HTTP archive holds just about every piece of software we have ever released.
Each release is held in a separate directory. Beta and final versions for each release
are within those directories. Below are shortcuts to specific parts of the archive
for people that want all of the source code without navigating through the pages specific
to each of the clients, servers, et cetera.

Current Releases

* link:https://www.opendap.org/pub/source[Source]
* link:https://www.opendap.org/pub/binary[Binary]

Old DODS releases (of historical interest only)

* link:https://www.opendap.org/pub/dods/[By Release]

== Continuous Integration Builds

We run Continuous Integration (CI) builds using 
link:https://travis-ci.org/OPENDAP/[Travis-CI] for the libdap, bes, olfs and pydap.
These builds are triggered when there is a push to the master branch of their GitHub repository.
These builds compile the code, run its automated tests and may do packaging tasks
(depending on the language).

== Version Control

We have moved most of our active projects to [GitHub](https://github.com/opendap).
You can clone the libdap, bes, and other projects' repositories from github.com/opendap.
We respond to problem tickets submitted on the site,
but our primary issue tracking system is Jira, which has open access for readers.

=== GitHub Links

There are many projects in our GitHub repository, here are some:

|=============
a|link:https://github.com/OPENDAP/libdap[libdap] |The C++ DAP2 library.
a|link:https://github.com/OPENDAP/hyrax[Hyrax] |The Hyrax server meta project.
a|link:https://github.com/OPENDAP/bes[BES], link:https://github.com/OPENDAP/olfs[OLFS]  |Child projects that are make up the Hyrax project.
|=============

=== Subversion (SVN)

A way to get older source code is to use anonymous access to our read-only SVN repository.
In 2015 we moved to GitHub for most of our active projects and switch the SVN repository
to read-only access. To access older code from SVN, you can...

* Visit the link:https://scm.opendap.org/svn/[svn repository].
This is a good way to read over source code if you have specific questions
about how a particular function has been implemented. 
* You can use a variety of subversion clients to read from the repository.
Generally, you will want to check out source code from the repository's link:https://scm.opendap.org/svn/trunk/['trunk'].
There are many subversion clients available and many plugins for IDEs.
* If you want to perform active development work on the older code,
please move it to GitHub and/or let us know so we can move it.
Email us at support@opendap.org.