OPeNDAP is a not-for-profit corporation that was formed back in 2000. Our goal is to develop technologies
that benefit many disciplines (not limited to oceanography, which is where we had our start), and that will also
facilitate access to and sharing of a wide variety of scientific data. To this end, we have developed
the DAP: a discipline-neutral Data Access Protocol. The DAP provides a simple and flexible web API
for data access and subsetting.

== What We Provide

As an organization, we provide a *data server* that you can use to make your data available via standard network protocols.
We have also provided and assisted in the development of various *toolkits* that enable access to your server's data
by just about any software written in Pyton, C, C++, or Java. Furthermore, several organizations have
added support for the DAP in their *analysis tools*, both commerical (Matlab and ArcGIS),
and open source (Jupyter notebooks and Panoply).

While we present the results of our work freely to the public in the form of open source
documentation, specifications, and software, we also offer our services as contractors.
Over the last two decades, we've worked with several agencies, groups, programs, and organizations,
including NASA, DataCube, Unidata, NOAA, OGC, and Python,
to help them develop implementations of our protocol that are tailored to their data.
These groups have created their own data servers and client tools,
thereby expanding the reach of our core technology.

== Our Goal

Ultimately, our goal is to make the OPeNDAP technology a core component of systems 
that provide machine-to-machine interoperability with semantic meaning in a highly distributed environment
of diverse datasets. In other words, our technology allows you to immediately access data that you require
in a form that you can use, from within your own applications.
In the fields of oceanography and atmospheric science,
we've already helped the research community make significant progress towards this end.
