= Design Documentation

== DODS Component Architecture

=== link:https://www.opendap.org/pdf/ESE-RFC-004v1.2.pdf[Data Access Protocol (DAP), version 2]

A technical description of the Data Access Protocol. This was submitted to NASA's Earth Science Data Systems Standards Process Group and has been accepted as a Recommended Standard (submitted on 8/8/2004, accepted 10/8/2007). The official 
link:https://earthdata.nasa.gov/standards/data-access-protocol-2[NASA ESE/RFC distribution point for DAP2] may provide a more up to date version and also has additional documentation regarding NASA/ESE's adoption of DAP2 as a community standard.

=== link:https://www.opendap.org/pdf/dap_objects.pdf[DODS Data Access Protocol, DRAFT, version 4 (DAP4)]

A DRAFT technical description of the DODS Data Access Protocol, version 4 (DAP4).

== Archive

These articles are older and are here mostly to provide
background and context for our current designs and implementations.

=== link:https://www.opendap.org/pub/dods/ps-docs/data-delivery-arch.ps[Data Delivery Architecture]

An overview of the architecture of the communication between the DODS client and server.

=== link:https://www.opendap.org/pub/dods/ps-docs/data-delivery-design.ps[Data Delivery Design]

The design for communication between the DODS client and server.

=== link:https://www.opendap.org/pub/dods/ps-docs/urls.ps[Uniform Resource Locators]

The specification for the use and extension of URLs in the DODS system.

=== link:https://www.opendap.org/pub/dods/ps-docs/api.ps[Data Access Protocol]

The methodology for exchanging data between the DODS client and server.

|===========
a|link:https://www.opendap.org/pub/dods/ps-docs/data-delivery-arch.ps[Data Delivery Architecture] a|
Data Delivery Architecture
a|link:https://www.opendap.org/pub/dods/ps-docs/data-delivery-design.ps[Data Delivery Design] a|
The design for communication between the DODS client and server.
a|link:https://www.opendap.org/pub/dods/ps-docs/urls.ps[Uniform Resource Locators] a|
The specification for the use and extension of URLs in the DODS system.
a|link:https://www.opendap.org/pub/dods/ps-docs/api.ps[Data Access Protocol] a|
The methodology for exchanging data between the DODS client and server.
|===========

