:Leonard Porrello <lporrel@gmail.com>:

== OLFS Installation

The OLFS comes with a default configuration that is compatible with the
default configuration of the BES. If you perform a default installation
of both, you should get a running Hyrax server that will be pre-populated
with test data suitable for running integrity tests.

=== 1. Install Tomcat

. Use yum to install tomcat.noarch: `sudo yum install tomcat.noarch`.
. Create the directory `/etc/olfs`, change its group to tomcat, 
and set it _group writable:_
+
....
mkdir /etc/olfs
chgrp tomcat /etc/olfs
chmod g+w /etc/olfs)
....
+
Alternatively, get Apache Tomcat-8.x from the Apache Software Foundation and 
install it wherever you'd like--for example, `/usr/local/`.

=== 2. Download the OLFS

Follow the steps below to download the latest OLFS distribution:

. Visit the 
  https://www.opendap.org/software/hyrax-data-server#block-hyraxversions-menu[Hyrax
  Data Server Page].
. Select the most recent in the list of _Available Versions_.
. Scroll down the following page until you reach the section titled 
  _Binaries for Hyrax x.x.x_.
. Directly underneath, you should see the OLFS download link, 
  named something like _OLFS_x.x.x._Web_Archive_File_. Click to download.
. The downloaded file will be named something like: _olfs-x.x.x-webapp.tgz_.

=== 3. Unpack

Unpack the downloaded jar file with the command `tar -xvf olfs-x.x.x-webapp.tgz`,
which will unpack the files directory called _olfs-x.x.x-webapp_.

=== 4. Install

Inside of the _olfs-x.x.x-webapp_ directory, locate opendap.war and copy it into
Tomcat's _webapps_ directory:

....
cp opendap.war /usr/share/tomcat/webapps
....

Or, if you installed tomcat from the ASF distribution, its web application directory, for example...

....
/usr/local/apache-tomcat-8.5.34/webapps
....

==== 5. Starting and Stopping the OLFS/Tomcat

If you followed this tutorial and are using a YUM-installed Tomcat, 
it should already be integrated into the system with a `tomcat` entry 
in `/etc/init.d` and you should be able to...

* *Start Tomcat*: `sudo service tomcat start`
* *Stop  Tomcat*: `sudo service tomcat stop`

You can verify that the server is running by visiting http://localhost:8080/opendap/.
If you have installed Hyrax on a virtual machine, replace _localhost_ with the 
virtual machine's IP address.

////
If you're replacing an older version of the OLFS you may need do one or more of:

* Remove the directory `$CATALINA_HOME/webapps/opendap` before
restarting Tomcat.
* Determine if the existing configuration information for the
OLFS needs to be updated. If things don't work after you start Tomcat,
you should compare your local configuration with the distributed one. Typically the local configuration or the OLFS will be located in the the `/etc/olfs` directory. The file `/etc/olfs/olfs.xml` should be compared to the new default
configuration located in
`$CATALINA_HOME/webapps/opendap/WEB-INF/conf/olfs.xml` If they differ
significantly:
** Backup your current configuration and move it out of the way:
+
`cd /etc; tar -cvzf ~/olfs_backup.tgz olfs; mv olfs ~/olfs_backup`
** Restart Tomcat. If the directory `/etc/olfs` exists and can be written to by
the Tomcat user then the OLFS will copy its default configuration set to the
`/etc/olfs` location at start up.
** Compare your previous configuration files `~/olfs_backup` with the new default
ones in `/etc/olfs` and adjust the new ones accordingly.


== Starting and Stopping the OLFS/Tomcat

The OLFS component of Hyrax is web application made up of several components all of which get started when Tomcat is started, assuming that the `opendap.war` has been placed in the $CATALINA_HOME/webapps directory prior to Tomcat start.
////
