= User Documentation

Many of these documents are old and no longer describe the software correctly. In general, the concepts they describe are correct, but many of the details have changed since these were written. If you have specific questions please contact us at support@opendap.org. Thanks for your patience while we work to update these!

* link:https://opendap.github.io/documentation/QuickStart.html[Quick Start Guide]
(link:https://opendap.github.io/documentation/QuickStart.pdf[pdf]):
Getting started with the OPeNDAP Software.
* https://opendap.github.io/documentation/UserGuideComprehensive.html[User's Guide]
(link:https://opendap.github.io/documentation/UserGuideComprehensive.pdf[pdf]):
Provides a full description of the OPeNDAP Software, and all the information needed to use a client, as well as to create clients, convert existing applications into clients, and set up servers.
* link:https://opendap.github.io/hyrax_guide/Master_Hyrax_Guide.html[Hyrax Data Server Documentation]
(link:https://opendap.github.io/hyrax_guide/Master_Hyrax_Guide.pdf[pdf]):
How to install a server.

Some of the non-reference documents are old and no longer describe the software correctly. In general, the concepts they describe are correct, but many of the details have changed since these were written. If you have specific questions please contact us at support@opendap.org. Thanks for your patience while we work to update these!

* link:http://docs.opendap.org/index.php/ProgrammerGuide[DODS C++ Programmer's Guide]
and
link:https://opendap.github.io/libdap4/html/index.html[DODS C++ Programming Reference]:
Provides information about the core software, programming tools, and the DAP (Data Access Protocol) classes.
* link:https://opendap.github.io/bes/html/index.html[BES C++ Programming Reference]:
Provides information about the BES framework
* link:http://docs.opendap.org/index.php/Documentation=Java_OPeNDAP_API_Documentation[DODS Java Programming Reference]:
Documentation for all the DODS Java classes including the core classes and the SQL server classes
* link: http://docs.opendap.org/index.php/Writing_a_Client[Writing an OPeNDAP client application]:
A tutorial that describes how to write an OPeNDAP client application using the C++ or Java toolkit.
* link:http://docs.opendap.org/index.php/Wiki_Testing/WritingAServer[Writing an OPeNDAP server]:
A tutorial that describes how to write an OPeNDAP server for a new datatype using the C++ toolkit. Much of this tutorial also applies to the Java toolkit.