= Available OPeNDAP Client Software

== OPeNDAP Clients

=== link:http://www.ncl.ucar.edu/[NCL - Scientific data analysis and visualization software]

NCL is a scientific data analysis and visualization software package freely available from
link:http://www.ncar.ucar.edu/[NCAR].

=== link:http://cdat.sf.net/[CDAT (Climate Data Analysis Tools)]

CDAT (developed at link:http://www-pcmdi.llnl.gov/[PCMDI])
is a software infrastructure that forms an integrated environment for solving model diagnosis problems. CDAT uses Python to seamlessly link together separate software subsystems and packages. CDAT version 3.3 is not distributed as a OPeNDAP client but can be re-linked to the OPeNDAP client libraries. CDAT version 4.0 will be distributed with that step integrated in the CDAT build.

=== OPeNDAP geturl

geturl is a simple command-line client for testing datasets. It is available as part of both the C++ and Java implementations.

For the C++ implementation of geturl, go to the 
link:https://www.opendap.org/software/libdap[DAP++ SDK page],
the client is included with the library.

=== Matlab 2012a

Matlab is one of the most compete data analysis tools available. Version 7.15 (aka Matlab 2012a), released on March 1, 2012 contains built-in support for access to OPeNDAP servers. To use this, you use the netCDF API to open remote datasets, inquire about their metadata as well as read and subsample/subset data. See
link:https://www.opendap.org/about/news/matlab-2012a-support[Matlab 2012a Includes Support for OPeNDAPView]
for more information.

=== OPeNDAP Matlab Toolkit (GUI)

The OPeNDAP netCDF client library is a DAP-enabled version of the netCDF API library.
link:http://www.unidata.ucar.edu/packages/netcdf/[netCDF]
is an interface for array-oriented data access and a library that provides an implementation of the interface developed and maintained by
link:http://www.unidata.ucar.edu/[UCAR/Unidata].

=== link:http://ferret.pmel.noaa.gov/Ferret/[Ferret]

Ferret is a data analysis and visualization package available from NOAA/PMEL that can access data.

=== link:http://www.iges.org/grads/[GrADS]

GrADS is a data analysis and visualization package for earth system data. It is available from
link:http://www.iges.org/cola.html[COLA].

=== link:http://my.unidata.ucar.edu/content/software/metapps/[IDV (Integrated Data Viewer)]

IDV is a Java application for visualizing and analyzing geoscience data. The IDV was developed at UCAR/Unidata and uses the
link:http://www.ssec.wisc.edu/~billh/visad.html)[VisAD library]
for data and display models as well as other Java utility packages.

=== link:http://ferret.pmel.noaa.gov/Ferret/LAS/[LAS (Live Access Server)]

LAS is a highly configurable Web server designed to provide flexible access to geo-referenced scientific data. LAS, by default, uses Ferret (see above) to produce plots of datasets which means the LAS can be configured to display data from OPeNDAP servers.

=== link:http://www.epic.noaa.gov/java/ncBrowse/[ncBrowse]

ncBrowse is a Java application that provides flexible, interactive graphical displays of data and attributes from a wide range of netCDF data file conventions. Version 1.3.3Beta5 and later can access OPeNDAP servers.

=== link:http://nco.sourceforge.net/[NCO (netCDF Operators)]

NCO is a set of command line tools that perform operations (e.g. average or concatenate) on netCDF or HDF files.

=== link:http://meteora.ucsd.edu/~pierce/ncview_home_page.html[ncview]

ncview is a visual browser for gridded data that is available from the ncview home page. We provide a version that can access data from OPeNDAP servers as well as local netCDF files.

To Download: Go to the NetCDF clients page.

=== link:http://www.epic.noaa.gov/epic/software/dchart/[DChart]

The Dapper Data Viewer (aka DChart) allows you to visualize and download in-situ oceanographic or atmospheric data from a Dapper OpenDap server. Features include an interactive map that is draggable, an in-situ station layer that allows you to select data stations, and a plot window that allows you to plot data from one or more stations. Three plot types are supported (profile, property-property, and time series) and users can interact directly with the plot to pan or zoom in and out

== Client Libraries

=== link:https://www.opendap.org/software/libdap[OPeNDAP DAP library]

The OPeNDAP C++ DAP library (libdap++.a) can be used to develop OPeNDAP client applications. For more information, see the
link:http://old.opendap.org/api/pguide-html[Programmers Guide]
and the
link:https://opendap.github.io/libdap4/html[Programmers Reference].

=== OPeNDAP Java API

The OPeNDAP Java DAP API can be used to develop OPeNDAP client applications. For more information, see the
link:https://www.opendap.org/api/javaDocs/[JavaDocs].

=== link:www.unidata.ucar.edu/packages/netcdf-java/[netCDF Java library]

The
link:http://www.unidata.ucar.edu/packages/netcdf-java/[Java implementation of netCDF]
comes with support for OPeNDAP servers enabled. Therefore, any application that uses this library can access data via the servers.

=== link:http://pydap.org/[pydods]

pydods is a simple Python library for interfacing with OPeNDAP servers. pydods was developed by Roberto A. F. De Almeida (Universidade de São Paulo).

== Other applications that can access DAP-compliant servers

=== Generic Web Browser

Because OPeNDAP servers are accessed through URLs, any application that can dereference a URL can access those servers. Thus, any generic web browser (e.g., Internet Explorer, Mozzilla, or Netscape) can access those data in a restricted manner. Since generic web browsers do not understand the OPeNDAP protocol, the user will need some understanding of the protocol. A brief explanation of how to access OPeNDAP data in a web browser is available at our FAQ 
'link:https://www.opendap.org/support/faq/general/using-web-browser[Using a Web Browser with OPeNDAP servers]'.

=== Spreadsheet Applications

Because OPeNDAP servers are accessed through URLs, any application that can dereference a URL can access those data. Since most spreadsheet applications (e.g., MS Excel and StarOffice) can open URLs, they can access those data in a restricted manner. However, since spreadsheet applications do not understand the OPeNDAP protocol, the user will need some understanding of the protocol. A brief explaination of how to access OPeNDAP data from a spreadsheet is available at our FAQ
link:https://www.opendap.org/support/faq/general/use-spreadsheet[Using a Spreadsheet Application with OPeNDAP servers].
